# Generated by Django 2.1 on 2018-08-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=192),
        ),
    ]
