# Generated by Django 2.1 on 2018-08-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180803_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
